# Generated by Django 5.2.6 on 2026-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
